# Modify from https://github.com/linuxserver/docker-qbittorrent

version: '2.1'

services:
  qbittorrent:
    build: ./app
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=18081
    volumes:
      - {{ qbittorrent_config }}:/config
      - {{ qbittorrent_downloads }}:/downloads
    ports:
      - 16882:16882
      - 16882:16882/udp
      - 18081:18081
    restart: unless-stopped
