---
- name: create docker-qbittorrent compose dir
  file:
    path: '{{ qbittorrent_root }}'
    state: directory

- name: upload compose file
  template:
    src: 'docker-compose.yml'
    dest: '{{ qbittorrent_root }}/docker-compose.yml'

- name: upload app image files
  copy:
    src: '{{ role_path }}/files/{{ item }}'
    dest: '{{ qbittorrent_root }}'
  loop:
    - app

- name: Start docker-qbittorrent
  command:
    cmd: docker-compose up -d
    chdir: '{{ qbittorrent_root }}'
