---
- name: install apt packages
  apt:
    name: '{{item}}'
  loop:
    - nginx
    # - python3-pip

# - name: install ngxtop
#   pip:
#     name: ngxtop
    # extra_args: '{{ pip_args | default(omit) }}'

- name: create nginx user home dir
  user:
    name: 'www-data'
    shell: /bin/bash
    home: '/home/www-data'
  register: user_result
  failed_when: "'used by process' not in user_result.msg"

- name: setup ssh public keys
  authorized_key:
    user: 'www-data'
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - authorized-keys/*

- name: upload nginx main config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: delete nginx built-in default site
  file: path=/etc/nginx/sites-enabled/default state=absent

# - name: upload nginx default site
#   template: src=default.conf dest=/etc/nginx/sites-enabled/default.conf

# - name: upload nginx resource file
#   copy: src={{role_path}}/files/holding dest=/var/www

- name: upload nginx site config
  template: src={{ item }} dest=/etc/nginx/sites-enabled/{{ item | basename }}
  notify: restart nginx
  with_fileglob:
    - nginx-sites/{{ ansible_hostname }}/*
