- hosts: nas
  become: true
  # become_user: root
  # vars:
  #   nextdata_exposed: true
  # vars_files:
  #   - secrets.yml
  #   - voyager-secrets.yml
  roles:
    # - common
    # - netdata
    # - docker
    # - nextcloud
    # - nginx
    - cloudflare-ddns
    # - qBittorrent-Enhanced
    # - docker-qbittorrent
    # - samba
    # - wireguard
    # - aria2
    # - bitwarden
