# Modify from https://github.com/oznu/docker-cloudflare-ddns#docker-compose

version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - EMAIL=bernylinville@devopsthink.org
      - API_KEY=xxxxxxxx
      - ZONE=devopsthink.org
      - SUBDOMAIN=cloud
      - PROXIED=false
