---
- name: create cloudflare-ddns compose dir
  file:
    path: "{{ cloudflare_ddns_path }}"
    state: directory

- name: upload compose file
  template:
    src: 'docker-compose.yml'
    dest: "{{ cloudflare_ddns_docker_compose_file_path }}"

- name: Start cloudflare-ddns
  command:
    cmd: docker-compose up -d
    chdir: "{{ cloudflare_ddns_path }}"
