# Modify from https://github.com/dani-garcia/bitwarden_rs/wiki/Using-Docker-Compose

version: '3'

services:
  bitwarden:
    image: vaultwarden/server:latest
    restart: always
    ports:
      - 10001:80
    volumes:
      - '{{ bitwarden_data }}:/data'
    environment:
      SIGNUPS_ALLOWED: 'true'   # set to false to disable signups
