---
- name: create nextcloud compose dir
  file:
    path: '{{ nextcloud_dir }}'
    state: directory

- name: upload compose file
  template:
    src: 'docker-compose.yml'
    dest: '{{ nextcloud_docker_compose }}'

- name: upload web image files
  copy:
    src: '{{ role_path }}/files/{{ item }}'
    dest: '{{ nextcloud_dir }}'
  loop:
    - web
    - app

# - name: Update nextcloud
#   command:
#     cmd: docker-compose build --pull
#     chdir: '{{ nextcloud_dir }}'

- name: Start nextcloud
  command:
    cmd: docker-compose up -d --build
    chdir: '{{ nextcloud_dir }}'
