# Modify from https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb/fpm/docker-compose.yml

version: '3'

services:
  db:
    image: mariadb  
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - '{{ nextcloud_db }}:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '{{ mysql_root_password }}'
      MYSQL_PASSWORD: '{{ nextcloud_mysql_password }}'
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  redis:
    image: redis:alpine
    restart: always

  app:
    # build: ./app
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - '{{ nextcloud_root }}:/var/www/html'
    environment:
      # OVERWRITEPROTOCOL: 'https'
      MYSQL_ROOT_PASSWORD: '{{ nextcloud_mysql_password }}'
      MYSQL_PASSWORD: '{{ nextcloud_mysql_password }}'
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    ports:
      - 8080:80
    volumes:
      - '{{ nextcloud_root }}:/var/www/html:ro'
    depends_on:
      - app

  cron:
    # build: ./app
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - '{{ nextcloud_root }}:/var/www/html'
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
