# Modify from https://github.com/linuxserver/docker-jellyfin

version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - {{ jellyfin_config }}:/config
      - {{ jellyfin_tvshows }}:/data/tvshows
      - {{ jellyfin_movies }}:/data/movies
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
