---
# - name: setup ssh public keys
#   authorized_key:
#     user: root
#     key: "{{ lookup('file', item) }}"
#   with_fileglob:
#     - authorized-keys/*

- name: install apt packages
  apt:
    name: '{{item}}'
  loop:
    - python3-apt
    - nethogs
    - htop
    - iotop
    # - nmon
    - neofetch
    - net-tools

- name: uninstall snap
  apt:
    name: '{{item}}'
    state: absent
    purge: yes
  loop:
    - snap
    - snapd
