---
# - name: install apt packages for docker
#   apt:
#     name: '{{item}}'
#   loop:
#     - apt-transport-https
#     - ca-certificates
#     - curl
#     - gnupg-agent
#     - software-properties-common

# - name: add apt repository key
#   apt_key:
#     url: 'https://download.docker.com/linux/debian/gpg'

# - name: add apt repository
#   apt_repository:
#     # repo: 'deb [arch=amd64] {{ docker_mirror_url | default("https://download.docker.com/linux/debian") }} {{ ansible_lsb.codename | lower }} stable'
#     repo: 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable'
#     update_cache: yes

- name: install apt packages
  apt:
    name: docker.io
    state: latest

- name: Add user to docker group
  user:
    name: kchou
    group: docker

- name: setup docker registry mirror
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  when: docker_registry_url is defined
  notify: restart docker

- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout
- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755
