---
- name: create bitwarden compose dir
  file:
    path: '{{ bitwarden_dir }}'
    state: directory

- name: upload compose file
  template:
    src: 'docker-compose.yml'
    dest: '{{ bitwarden_docker_compose }}'

- name: Update bitwarden
  command:
    cmd: docker-compose pull
    chdir: '{{ bitwarden_dir }}'

- name: Start bitwarden
  command:
    cmd: docker-compose up -d
    chdir: '{{ bitwarden_dir }}'
