---
- name: create aria2 compose dir
  file:
    path: '{{ aria2_dir }}'
    state: directory

- name: upload compose file
  template:
    src: 'docker-compose.yml'
    dest: '{{ aria2_docker_compose }}'

- name: Start aria2
  command:
    cmd: docker-compose up -d
    chdir: '{{ aria2_dir }}'
